### ISSUE TITLE
Feat : Adding the QRWallet class

### ISSUE THREAD

**Issue by Boredalien248** [CMPUT301W23T32/lordofthewings#40]

**Comment by mkhan1107** [comment]
https://github.com/orgs/CMPUT301W23T32/projects/1/views/1?filterQuery=01.01.01&pane=issue&itemId=19850892
https://github.com/orgs/CMPUT301W23T32/projects/1/views/1?filterQuery=01.03.01&pane=issue&itemId=19913992
https://github.com/orgs/CMPUT301W23T32/projects/1/views/1?filterQuery=01.05.01&pane=issue&itemId=19914006
https://github.com/orgs/CMPUT301W23T32/projects/1/views/1?filterQuery=01.06.01&pane=issue&itemId=19914014
https://github.com/orgs/CMPUT301W23T32/projects/1/views/1?filterQuery=01.02.01&pane=issue&itemId=19913980
