### ISSUE TITLE
Bug: Add Location Crashing the App

### ISSUE THREAD

**Issue by KrishLal** [CMPUT301W23T32/lordofthewings#67]
Installed the app on my device, granted it a one time location permission.

Every time I try to add a location, It crashes the app.

**Comment by mkhan1107** [comment]
I tried it on an android device I possess that is on the latest update and it worked fine, did not crash. I did location permission as well, displayed my location textually.

**Comment by mkhan1107** [comment]
I also granted it one time location premission
